"use client";

import { useState, type FormEvent } from "react";
import { CalendarDays, Check, CheckCheck, Clock3, Flag, Info, LoaderCircle, Megaphone, Plus, Save, Shuffle, Sparkles, X } from "lucide-react";
import { ApiError } from "@season/api-client";
import { localParts, validateSchedule } from "@season/core";
import type { Command, Contact, Game, Registration, Tournament, Workspace } from "@season/types";
import { localDateTime, localToInstant } from "@/lib/local-time";
import { Badge, gameTime, Modal, playAreaLabel, Status, TeamMark, teamName } from "./shared";

export type Dialog = { type: "registration" | "announcement" | "division" | "venue" | "generate" | "publish" | "rules" } | { type: "game" | "move"; game: Game } | { type: "player"; team: Registration } | { type: "contact"; contact?: Contact };
type Props = { dialog: Dialog; tournament: Tournament; busy: boolean; execute: (command: Command) => Promise<Workspace | undefined>; onClose: () => void; onChange: (dialog: Dialog) => void };
export function ActionDialog(props: Props) { return <DialogContent key={`${props.dialog.type}-${"game" in props.dialog ? props.dialog.game.id : "contact" in props.dialog ? props.dialog.contact?.id ?? "" : ""}`} {...props} />; }

function DialogContent({ dialog, tournament, busy, execute, onClose, onChange }: Props) {
  const [error, setError] = useState("");
  const [details, setDetails] = useState<string[]>([]);
  const [audience, setAudience] = useState<"all" | "specific">("all");
  const [contactIds, setContactIds] = useState<string[]>([]);
  const [homeScore, setHomeScore] = useState("game" in dialog ? String(dialog.game.homeScore ?? 0) : "0");
  const [awayScore, setAwayScore] = useState("game" in dialog ? String(dialog.game.awayScore ?? 0) : "0");
  const [fieldId, setFieldId] = useState("game" in dialog ? dialog.game.fieldId ?? tournament.fields[0]?.id ?? "" : "");
  const [playAreas, setPlayAreas] = useState<string[]>([""]);
  const [start, setStart] = useState("game" in dialog && dialog.game.start ? localDateTime(dialog.game.start, tournament.timezone) : `${tournament?.startsOn ?? ""}T08:00`);
  const [force, setForce] = useState(false);
  const [seed, setSeed] = useState(() => Math.floor(Math.random() * 1_000_000));
  const game = "game" in dialog ? dialog.game : undefined;
  const editingContact = dialog.type === "contact" ? dialog.contact : undefined;
  function readImage(file: File | undefined, onLoad: (dataUrl: string) => void) {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => { if (typeof reader.result === "string") onLoad(reader.result); };
    reader.readAsDataURL(file);
  }
  const titles = { registration: "Add a team", announcement: "New announcement", division: "Add a division", venue: "Add a venue", contact: editingContact ? "Edit contact" : "Add a contact", generate: "Generate tournament schedule", publish: "Publish schedule", rules: "Tournament settings", game: "Game center", move: "Move game", player: "Add a player" };
  const labels = { registration: "Add team", announcement: "Publish announcement", division: "Add division", venue: "Add venue", contact: editingContact ? "Save contact" : "Add contact", generate: "Generate schedule", publish: "Publish schedule", rules: "Save settings", game: "Save final score", move: "Save game time", player: "Add player" };
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setDetails([]);
    const form = new FormData(event.currentTarget);
    const text = (name: string) => String(form.get(name) ?? "");
    const number = (name: string) => Number(form.get(name));
    const tournamentId = tournament?.id ?? "";
    try {
      let command: Command;
      switch (dialog.type) {
        case "registration": command = { type: "register_team", tournamentId, data: { teamName: text("teamName"), clubName: text("clubName"), divisionId: text("divisionId"), city: text("city"), coachName: text("coachName"), coachEmail: text("coachEmail") } }; break;
        case "announcement": command = { type: "announce", tournamentId, data: { subject: text("subject"), body: text("body"), contactIds: audience === "specific" ? contactIds : [] } }; break;
        case "division": command = { type: "add_division", tournamentId, division: { name: text("name"), format: text("format") as Tournament["divisions"][number]["format"], maxTeams: number("maxTeams"), guaranteedGames: number("guaranteedGames"), advancePerPool: number("advancePerPool"), entryFeeCents: Math.round(number("entryFeeDollars") * 100), earliestTime: text("earliestTime"), latestTime: text("latestTime"), eligibility: { earliestBirthdate: text("earliestBirthdate"), latestBirthdate: text("latestBirthdate"), rosterMin: number("rosterMin"), rosterMax: number("rosterMax"), requiredDocuments: ["age_verification"], waiverVersion: 1 } } }; break;
        case "venue": command = { type: "add_venue", tournamentId, venue: { name: text("name"), address: text("address"), playAreas: playAreas.filter((name) => name.trim().length > 0).map((name) => ({ name })) } }; break;
        case "contact": command = editingContact ? { type: "update_contact", tournamentId, contactId: editingContact.id, name: text("name"), email: text("email"), note: text("note") } : { type: "add_contact", tournamentId, name: text("name"), email: text("email"), note: text("note") }; break;
        case "generate": command = { type: "generate_schedule", tournamentId, seed: number("seed") }; break;
        case "publish": command = { type: "publish_schedule", tournamentId }; break;
        case "rules": command = { type: "update_tournament", tournamentId, name: text("name"), status: text("status") as Tournament["status"], rules: tournament.games.length ? tournament.rules : { ...tournament.rules, gameMinutes: number("gameMinutes"), bufferMinutes: number("bufferMinutes"), restMinutes: number("restMinutes"), maxGamesPerDay: number("maxGamesPerDay") } }; break;
        case "game": command = { type: "score_game", tournamentId, gameId: dialog.game.id, version: dialog.game.version, homeScore: Number(homeScore), awayScore: Number(awayScore), forfeit: form.get("forfeit") === "on" }; break;
        case "move": command = { type: "move_game", tournamentId, gameId: dialog.game.id, version: dialog.game.version, fieldId, start: localToInstant(start, tournament.timezone), force, reason: text("reason") }; break;
        case "player": command = { type: "add_player", tournamentId, registrationId: dialog.team.id, player: { firstName: text("firstName"), lastName: text("lastName"), birthdate: text("birthdate"), jerseyNumber: text("jerseyNumber") } }; break;
      }
      await execute(command);
      onClose();
    } catch (error) { setError(error instanceof Error ? error.message : "Unable to save changes"); if (error instanceof ApiError) setDetails(error.details); }
  }
  let moveStart: Date | null = null;
  let moveError = "";
  if (dialog.type === "move") {
    try { moveStart = new Date(localToInstant(start, tournament.timezone)); }
    catch (error) { moveError = (error as Error).message; }
  }
  const moveIssues = dialog.type === "move" && moveStart ? validateSchedule({ ...tournament, games: tournament.games.map((item) => item.id === dialog.game.id ? { ...item, fieldId, start: moveStart!.toISOString(), end: new Date(moveStart!.valueOf() + tournament.rules.gameMinutes * 60000).toISOString(), status: "scheduled" } : item) }).filter((issue) => issue.gameId === dialog.game.id || issue.conflictingGameId === dialog.game.id || issue.code === "daily_limit") : [];
  return <Modal title={titles[dialog.type]} onClose={onClose} wide={dialog.type === "division"} full={dialog.type === "announcement"}><form onSubmit={submit} className="dialog-form">
    {error && <div role="alert" className="form-error"><strong>{error}</strong>{details.length > 0 && <ul>{details.map((detail, index) => <li key={index}>{detail}</li>)}</ul>}</div>}
    {dialog.type === "registration" && <><label>Team name<input name="teamName" required minLength={2} maxLength={80} autoFocus placeholder="Team name" /></label><div className="form-grid"><label>Club<input name="clubName" maxLength={100} /></label><label>Home city<input name="city" maxLength={100} /></label></div><label>Division<select name="divisionId" required>{tournament.divisions.map((division) => <option key={division.id} value={division.id}>{division.name}</option>)}</select></label><div className="form-grid"><label>Coach name<input name="coachName" required minLength={2} maxLength={100} /></label><label>Coach email<input name="coachEmail" type="email" required /></label></div><div className="form-note">No payment is collected yet.</div></>}
    {dialog.type === "announcement" && <><label>Audience<select value={audience} onChange={(event) => { setAudience(event.target.value as "all" | "specific"); setContactIds([]); }}><option value="all">All tournament contacts</option><option value="specific">Specific contacts</option></select></label>{audience === "specific" && <div className="field"><span className="field-hint">Select the contacts who should receive this announcement.</span><div className="contact-picker">{tournament.contacts.map((contact) => <label key={contact.id} className="checkbox-label"><input type="checkbox" checked={contactIds.includes(contact.id)} onChange={(event) => setContactIds((current) => event.target.checked ? [...current, contact.id] : current.filter((id) => id !== contact.id))} /><span><strong>{contact.name}</strong>{contact.note && <small> — {contact.note}</small>}</span></label>)}</div></div>}{!tournament.contacts.length && <div className="form-note">No contacts yet. Add a contact before sending an announcement.</div>}<label>Subject<input name="subject" minLength={3} maxLength={150} required placeholder="Announcement subject" autoFocus /></label><label>Message<textarea name="body" rows={6} minLength={1} maxLength={5000} required placeholder="Write your announcement..." /></label><div className="form-note">Delivered by email to the selected contacts.</div></>}
    {dialog.type === "division" && <><label>Division name<input name="name" required minLength={2} maxLength={80} placeholder="U12 Boys Elite" autoFocus /></label><div className="form-grid"><label>Format<select name="format"><option value="pool_to_bracket">Pool play into bracket</option><option value="round_robin">Round robin</option><option value="pool_only">Pool play only</option><option value="single_elim">Single elimination</option><option value="double_elim">Double elimination</option></select></label><label>Maximum teams<input name="maxTeams" type="number" min={2} max={1024} defaultValue={16} required /></label><label>Guaranteed games<input name="guaranteedGames" type="number" min={1} max={12} defaultValue={3} required /></label><label>Advance per pool<input name="advancePerPool" type="number" min={1} max={8} defaultValue={2} required /></label><label>Entry fee ($)<input name="entryFeeDollars" type="number" min={0} max={100000} step={0.01} defaultValue={450} required /></label><div /><label>Earliest game time<input name="earliestTime" type="time" defaultValue="08:00" required /></label><label>Latest finish time<input name="latestTime" type="time" defaultValue="18:00" required /></label><label hidden>Earliest eligible birthdate<input name="earliestBirthdate" type="date" defaultValue="2014-01-01" /></label><label hidden>Latest eligible birthdate<input name="latestBirthdate" type="date" defaultValue="2015-12-31" /></label><label>Minimum players<input name="rosterMin" type="number" min={1} max={100} defaultValue={7} required /></label><label>Maximum players<input name="rosterMax" type="number" min={1} max={100} defaultValue={18} required /></label></div></>}
    {dialog.type === "venue" && <><label>Venue name<input name="name" minLength={2} maxLength={100} required placeholder="Zilker Sports Complex" autoFocus /></label><label>Venue address<input name="address" minLength={2} maxLength={200} required placeholder="2100 Barton Springs Rd, Austin, TX" /></label><div className="play-area-field"><span className="play-area-label">{playAreaLabel(tournament.sport)}s</span><div className="play-area-chips">{playAreas.map((name, index) => <div className="play-area-chip" key={index}><input aria-label={`${playAreaLabel(tournament.sport)} name ${index + 1}`} value={name} onChange={(event) => setPlayAreas((current) => current.map((value, position) => position === index ? event.target.value : value))} minLength={2} maxLength={80} required placeholder={`${playAreaLabel(tournament.sport)} ${index + 1}`} />{playAreas.length > 1 && <button type="button" aria-label={`Remove ${playAreaLabel(tournament.sport).toLowerCase()} ${index + 1}`} onClick={() => setPlayAreas((current) => current.filter((_, position) => position !== index))}><X size={12} /></button>}</div>)}<button type="button" className="play-area-add" onClick={() => setPlayAreas((current) => [...current, ""])}><Plus size={13} />Add {playAreaLabel(tournament.sport).toLowerCase()}</button></div></div><Badge>{tournament.sport}</Badge></>}
    {dialog.type === "contact" && <><label>Name<input name="name" required autoFocus minLength={1} maxLength={100} defaultValue={editingContact?.name} placeholder="Coach name" /></label><label>Email address<input name="email" type="email" required defaultValue={editingContact?.email} placeholder="coach@example.com" /></label><label>Note<input name="note" maxLength={200} defaultValue={editingContact?.note} placeholder="Optional note" /></label></>}
    {dialog.type === "generate" && <><div className="dialog-feature"><Sparkles size={30} /><h3>{tournament.games.length ? "Reschedule remaining games" : "Build your tournament schedule"}</h3><p>{tournament.registrations.filter((team) => team.status === "accepted").length} accepted teams · {tournament.divisions.length} divisions · {tournament.fields.length} fields</p></div>{tournament.registrations.some((team) => team.status === "submitted") && <div className="form-note"><Info size={15} />{tournament.registrations.filter((team) => team.status === "submitted").length} team{tournament.registrations.filter((team) => team.status === "submitted").length === 1 ? "" : "s"} still pending review won&apos;t be included in this schedule. Accept or decline them first if you want them added.</div>}<input type="hidden" name="seed" value={seed} />{tournament.games.length > 0 && <button type="button" className="text-link" onClick={() => setSeed(Math.floor(Math.random() * 1_000_000))}><Shuffle size={14} />Don&apos;t like this arrangement? Shuffle it</button>}</>}
    {dialog.type === "publish" && <><div className="dialog-feature"><CheckCheck size={30} /><h3>{tournament.publishedAt ? "Publish schedule changes?" : "Ready for game day?"}</h3><p>{tournament.games.filter((game) => game.status !== "bye").length} games · {tournament.registrations.filter((team) => team.status === "accepted").length} teams</p></div><p className="muted">{tournament.publishedAt ? "Only teams affected by schedule changes receive a new in-app notification." : "The schedule becomes visible on the public tournament page."}</p></>}
    {dialog.type === "rules" && <><label>Tournament name<input name="name" defaultValue={tournament.name} required minLength={3} maxLength={100} /></label><label>Status<select name="status" defaultValue={tournament.status}>{["draft", "registration_open", "registration_closed", "scheduled", "in_progress", "completed", "archived"].map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></label><fieldset disabled={tournament.games.length > 0}><legend>Competition rules</legend><div className="form-grid"><label>Game duration (minutes)<input name="gameMinutes" type="number" min={5} max={240} defaultValue={tournament.rules.gameMinutes} required /></label><div className="field"><label>Minimum {playAreaLabel(tournament.sport).toLowerCase()} buffer (minutes)<input name="bufferMinutes" type="number" min={0} max={120} defaultValue={tournament.rules.bufferMinutes} required /></label><small className="field-hint">The shortest gap left between two games on the same {playAreaLabel(tournament.sport).toLowerCase()}.</small></div><div className="field"><label>Minimum team rest (minutes)<input name="restMinutes" type="number" min={0} max={360} defaultValue={tournament.rules.restMinutes} required /></label><small className="field-hint">The shortest gap left between two games for the same team.</small></div><div className="field"><label>Maximum games per team per day<input name="maxGamesPerDay" type="number" min={1} max={12} defaultValue={tournament.rules.maxGamesPerDay} required /></label><small className="field-hint">No team will be scheduled for more games than this on the same day.</small></div></div></fieldset></>}
    {dialog.type === "game" && game && <><div className="game-dialog-meta"><Badge>{tournament.divisions.find((division) => division.id === game.divisionId)?.name}</Badge><Status status={game.status} /><span>{game.label}</span></div><div className="score-editor"><div><TeamMark name={teamName(tournament, game.homeId)} /><strong>{teamName(tournament, game.homeId)}</strong><input aria-label="Home score" type="number" min={0} max={999} value={homeScore} onChange={(event) => setHomeScore(event.target.value)} required /></div><span className="score-separator">:</span><div><TeamMark name={teamName(tournament, game.awayId)} index={2} /><strong>{teamName(tournament, game.awayId)}</strong><input aria-label="Away score" type="number" min={0} max={999} value={awayScore} onChange={(event) => setAwayScore(event.target.value)} required /></div></div><div className="game-location"><Clock3 size={15} />{gameTime(game.start, tournament.timezone)}<Flag size={15} />{tournament.fields.find((field) => field.id === game.fieldId)?.name ?? "No field"}</div><label className="checkbox-label"><input type="checkbox" name="forfeit" defaultChecked={game.status === "forfeit"} />Forfeit result</label>{game.needsResolution && <div className="form-error">A corrected upstream result changed this matchup. Manager resolution is required before another score can be recorded.</div>}<div className="game-operation-actions">{!["final", "forfeit", "bye"].includes(game.status) && <><button type="button" className="button small" onClick={() => onChange({ type: "move", game })}><CalendarDays size={15} />Move game</button>{["in_progress", "postponed", "cancelled"].filter((status) => status !== game.status).map((status) => <button type="button" className="button small" key={status} disabled={busy} onClick={async () => { try { await execute({ type: "game_status", tournamentId: tournament.id, gameId: game.id, version: game.version, status: status as "in_progress" | "postponed" | "cancelled" }); onClose(); } catch (error) { setError((error as Error).message); } }}>{status === "in_progress" ? "Start game" : status === "postponed" ? "Postpone" : "Cancel game"}</button>)}</>}</div></>}
    {dialog.type === "move" && game && <><p><strong>{teamName(tournament, game.homeId)}</strong> vs <strong>{teamName(tournament, game.awayId)}</strong></p><label>Field<select value={fieldId} onChange={(event) => setFieldId(event.target.value)}>{tournament.fields.map((field) => <option key={field.id} value={field.id}>{field.name}</option>)}</select></label><label>Start ({tournament.timezone})<input type="datetime-local" value={start} onChange={(event) => setStart(event.target.value)} required /></label>{moveStart && <p className="form-note">{localParts(moveStart.toISOString(), tournament.timezone).date}, {gameTime(moveStart.toISOString(), tournament.timezone)}</p>}{moveError ? <div className="form-error">{moveError}</div> : moveIssues.length > 0 ? <><div className="form-error"><strong>Schedule conflicts</strong><ul>{moveIssues.map((issue, index) => <li key={index}>{issue.message}</li>)}</ul></div><label className="checkbox-label"><input type="checkbox" checked={force} onChange={(event) => setForce(event.target.checked)} />Force override these hard constraints</label>{force && <label>Override reason<textarea name="reason" required minLength={10} maxLength={500} rows={3} /></label>}</> : <div className="success-text"><Check size={16} /> No scheduling conflicts</div>}</>}
    {dialog.type === "player" && <><Badge>{dialog.team.teamName}</Badge><div className="form-grid"><label>First name<input name="firstName" minLength={1} maxLength={80} required autoFocus /></label><label>Last name<input name="lastName" minLength={1} maxLength={80} required /></label><label>Birthdate<input name="birthdate" type="date" required /></label><label>Jersey number<input name="jerseyNumber" maxLength={3} /></label></div><div className="form-note">Sample data only. Do not enter real minors’ information.</div></>}
    <div className="modal-actions"><button type="button" className="button" onClick={onClose}>Cancel</button><button className="button primary" disabled={busy || (dialog.type === "move" && moveIssues.length > 0 && !force) || (dialog.type === "game" && (!game?.homeId || !game?.awayId || game.needsResolution || game.status === "cancelled")) || (dialog.type === "announcement" && (!tournament.contacts.length || (audience === "specific" && !contactIds.length)))}>{busy ? <LoaderCircle size={16} className="spin" /> : dialog.type === "generate" ? <Sparkles size={16} /> : dialog.type === "announcement" ? <Megaphone size={16} /> : <Save size={16} />}{labels[dialog.type]}</button></div>
  </form></Modal>;
}